### ISSUE TITLE
section_min=0 crashes R session

### ISSUE THREAD

**Issue by max-alletsee** [hendr1km/dropout#10]
I noticed that setting `section_min=0` crashes the full R session.

While this is certainly unexpcted/malignant user behaviour, crashing the whole session may have consequences for the data processing workflow and the user's experience.

It would be good if the function rejects the input or deals with it more gracefully.
(I discovered this in the context of the JOSS review, but this is technically not part of the review criteria itself.)

Here is a simple reproducible example:

    library(dropout)
    data(flying)
    drop_summary(flying, section_min=0, last_col="location_census_region")

I am using R 4.2.2 on a Windows 10 machine. The dropout package version is 2.1.0; the Rcpp package version (which I suspect as the underlying cause) is 1.0.12.

**Comment by medewitt** [comment]
To @max-alletsee 's point, you could add something to the body of this function:

```
drop_summary <- function(data, last_col = NULL, section_min = 3) {
   if(section_min < 1) {
  stop("`section_min` must be 1 or greater")
}

....


}
```

**Comment by hendr1km** [comment]
Thanks a lot. Added this to prevent the session from crashing.
