### ISSUE TITLE
Unable to install on R <= 4.0

### ISSUE THREAD

**Issue by medewitt** [hendr1km/dropout#2]
## Problem

Unable to install on R version 3.6

## Solution

Two potential solutions

1. Update the minimum R version support to >= 4.0.0
2. Remove the use of the native pipe (`|>`) (e.g., https://github.com/hendr1km/dropout/blob/f125589d5f00435cc7c3c6feffc055b895ed51fe/R/drop_detect.R#L30)

As part of [the joss review](https://github.com/openjournals/joss-reviews/issues/6181#issuecomment-1958254503)

**Comment by hendr1km** [comment]
First of all thank you for all your feedback. 

Regarding this issue I have removed the native pipe from the code. In the test run the updated dev version worked now with R 3.6

**Comment by medewitt** [comment]
Excellent! Last thing is just to change your DESCRIPTION to reflect R >= 3.5

https://github.com/hendr1km/dropout/blob/84572aa8d33d6d35430d4a43fec6db71cd8217b3/DESCRIPTION#L25

That's the minimum R version supported by dplyr.

**Comment by hendr1km** [comment]
Good to know. Thank you - adjusted this.
