### ISSUE TITLE
Joss Review--Supported claim of scalability

### ISSUE THREAD

**Issue by medewitt** [hendr1km/dropout#6]
>The dropout package’s scalability is enhanced by the integration of C++ code through the Rcpp package, developed by Eddelbuettel et al. (2023). This incorporation makes dropout particularly effective for analyzing large survey datasets.

Unless this is supported with experimental results, I wouldn't include the second sentence in the paper. I totally understand that the C++ implementation should provide some speed, but unless experimentally supported I wouldn't include it. 

Part of [this joss review](https://github.com/openjournals/joss-reviews/issues/6181#issuecomment-1958254503)

**Comment by hendr1km** [comment]
I have removed this part from the paper
