### ISSUE TITLE
JOSS Review: Citation of flying data

### ISSUE THREAD

**Issue by max-alletsee** [hendr1km/dropout#8]
One of the JOSS criteria is a complete list of references, including datasets.

While you are using a dataset that comes with the package installation and you provide a citation in the package documentation, I would encourage you to also cite it directly in the software paper.

(As part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/6181#issuecomment-1880197553).)

**Comment by hendr1km** [comment]
Thank you for your feedback. I have added the citation to the paper.
