### ISSUE TITLE
JOSS Review: Removing Installation Instructions From the Software Paper

### ISSUE THREAD

**Issue by max-alletsee** [hendr1km/dropout#9]
I saw that you have recently added installation instructions directly in the software paper (https://github.com/hendr1km/dropout/commit/044ea3196aff76d8034cd3decf1c31e21748acdc).

JOSS guidelines ask for installation instructions in the software **documentation** (which you have), but not specifically in the software **paper**. While this is not technically wrong, it is somewhat uncommon and I do not see the need for it as you follow the standard CRAN process.

Therefore, I would ask you to consider removing the installation part from the paper and keep it only in the software documentation. This is just a suggestion, not a barrier for approval.

(As part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/6181#issuecomment-1880197553).)

**Comment by hendr1km** [comment]
Thanks for the clarification. I have removed this part.
